import express from 'express';
import http from 'http';
import cors from 'cors';
import mysql from 'mysql2/promise';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import { Server as SocketServer } from 'socket.io';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = Number(process.env.PORT || 3000);
const DATABASE_URL = process.env.DATABASE_URL || process.env.DRIZZLE_DATABASE_URL;
if (!DATABASE_URL) throw new Error('DATABASE_URL is required');
const pool = mysql.createPool({ uri: DATABASE_URL, ssl: { rejectUnauthorized: false }, connectionLimit: 8, dateStrings: true });
const app = express();
const server = http.createServer(app);
const io = new SocketServer(server, { cors: { origin: true, credentials: true } });
app.use(cors({ origin: true, credentials: true }));
app.use(express.json({ limit: '4mb' }));
app.use(express.static(path.join(__dirname, 'public')));

const q = async (sql, params = []) => (await pool.query(sql, params))[0];
const execSql = async (sql, params = []) => (await pool.execute(sql, params))[0];
const secret = () => process.env.JWT_SECRET || process.env.MANUS_JWT_SECRET || 'oneira-dev-secret-change-me';
const sign = user => jwt.sign({ id: user.id, role: user.role, storeId: user.store_id || null, storeName: user.store_name || user.storeName || null, name: user.name }, secret(), { expiresIn: '7d' });
const tokenFrom = req => (req.headers.authorization || '').replace(/^Bearer\s+/i, '') || '';
const auth = (roles = []) => (req, res, next) => {
  try {
    req.user = jwt.verify(tokenFrom(req), secret());
    if (roles.length && !roles.includes(req.user.role)) return res.status(403).json({ error: '无权限' });
    next();
  } catch { res.status(401).json({ error: '登录已失效' }); }
};
const json = value => (value == null ? {} : typeof value === 'string' ? JSON.parse(value) : value);
const reportRevenue = payload => Number(payload?.totalRevenue ?? payload?.revenue ?? 0);
async function log(req, action, entity, entityId, detail = {}) {
  await execSql('INSERT INTO audit_logs(user_id,action,entity,entity_id,detail) VALUES(?,?,?,?,?)', [req.user?.id || null, action, entity, String(entityId ?? ''), JSON.stringify(detail)]);
}
function changed() { io.emit('data:changed', { at: new Date().toISOString() }); }

async function migrateAndSeed() {
  await execSql('CREATE TABLE IF NOT EXISTS schema_migrations (id VARCHAR(120) PRIMARY KEY, applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)');
  const [[done]] = await pool.query('SELECT id FROM schema_migrations WHERE id=?', ['001_initial']);
  if (!done) {
    const sql = await (await import('fs/promises')).readFile(path.join(__dirname, 'db/migrations/001_initial.sql'), 'utf8');
    for (const statement of sql.split(';').map(x => x.trim()).filter(Boolean)) {
      if (!statement.toLowerCase().startsWith('create table if not exists schema_migrations')) await execSql(statement);
    }
    await execSql('INSERT INTO schema_migrations(id) VALUES(?)', ['001_initial']);
  }
  const stores = await q('SELECT id FROM stores WHERE name=? LIMIT 1', ['咸阳店']);
  let storeId = stores[0]?.id;
  if (!storeId) storeId = (await execSql('INSERT INTO stores(name,address,login_code,manager_name) VALUES(?,?,?,?)', ['咸阳店', '咸阳市', 'BAKE2024', '李店长'])).insertId;
  if (!(await q("SELECT id FROM users WHERE name=? AND role='store' LIMIT 1", ['李店长'])).length) await execSql("INSERT INTO users(name,store_id,role) VALUES(?,?, 'store')", ['李店长', storeId]);
  const hash = await bcrypt.hash('oneira2026', 10);
  const [[reportNameColumn]] = await pool.query("SELECT COUNT(*) AS count FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='daily_reports' AND column_name='submitted_by_name'");
  if (!Number(reportNameColumn.count)) await execSql('ALTER TABLE daily_reports ADD COLUMN submitted_by_name VARCHAR(120) NULL AFTER submitted_by');
  if (!(await q("SELECT id FROM users WHERE name='运营' AND role='ops' LIMIT 1")).length) await execSql("INSERT INTO users(name,role,password_hash) VALUES('运营','ops',?)", [hash]);
  if (!(await q("SELECT id FROM users WHERE name='管理员' AND role='admin' LIMIT 1")).length) await execSql("INSERT INTO users(name,role,password_hash) VALUES('管理员','admin',?)", [hash]);
  const [[reviewMigration]] = await pool.query('SELECT id FROM schema_migrations WHERE id=?', ['002_reviews_annotations']);
  if (!reviewMigration) {
    const sql = await (await import('fs/promises')).readFile(path.join(__dirname, 'db/migrations/002_reviews_annotations.sql'), 'utf8');
    for (const statement of sql.split(';').map(x => x.trim()).filter(Boolean)) await execSql(statement);
    await execSql('INSERT INTO schema_migrations(id) VALUES(?)', ['002_reviews_annotations']);
  }
  if (!Number((await q('SELECT COUNT(*) AS count FROM report_fields'))[0].count)) await execSql("INSERT INTO report_fields(label,`key`,field_type,unit,required,sort_order) VALUES ('营业额','revenue','number','元',1,1),('客单量','orders','number','单',1,2),('损耗率','wasteRate','number','%',1,3),('会员新增','members','number','人',0,4)");
  const [[rankingMigration]] = await pool.query('SELECT id FROM schema_migrations WHERE id=?', ['003_ranking_ai']);
  if (!rankingMigration) { const sql = await (await import('fs/promises')).readFile(path.join(__dirname, 'db/migrations/003_ranking_ai.sql'), 'utf8'); for (const statement of sql.split(';').map(x => x.trim()).filter(Boolean)) await execSql(statement); await execSql('INSERT INTO schema_migrations(id) VALUES(?)', ['003_ranking_ai']); }
}

app.get('/api/health', async (_req, res) => { try { await q('SELECT 1 AS ok'); res.json({ ok: true, version: '5.2.0-manus-space', service: 'oneira-workbench' }); } catch { res.status(503).json({ ok: false }); } });
app.get('/api/sync/version', (_req, res) => res.json({ at: new Date().toISOString() }));
app.get('/api/public/stores', async (_req, res) => res.json(await q("SELECT id,name FROM stores WHERE status='active' ORDER BY id")));
app.post('/api/auth/store-login', async (req, res) => { const storeName = String(req.body.storeName || '').trim(); const name = String(req.body.name || '').trim().slice(0, 120); const code = String(req.body.code || '').trim(); if (!storeName || !code || !name) return res.status(400).json({ error: '请选择门店并填写本次提交姓名和门店口令' }); const rows = await q("SELECT s.id AS store_id,s.name AS store_name,u.id AS user_id FROM stores s LEFT JOIN users u ON u.store_id=s.id AND u.role='store' WHERE s.name=? AND s.login_code=? AND s.status='active' ORDER BY u.id LIMIT 1", [storeName, code]); if (!rows.length) return res.status(401).json({ error: '门店或口令错误' }); const identity = { id: rows[0].user_id || null, name, role: 'store', store_id: rows[0].store_id, store_name: rows[0].store_name }; const token = sign(identity); res.json({ token, user: { id: identity.id, name, role: 'store', storeId: identity.store_id, storeName: identity.store_name } }); });
app.post('/api/auth/staff-login', async (req, res) => { const { name, password, role } = req.body; const rows = await q('SELECT * FROM users WHERE name=? AND role=?', [name, role]); if (!rows.length || !(await bcrypt.compare(password || '', rows[0].password_hash || ''))) return res.status(401).json({ error: '账号或密码错误' }); const token = sign(rows[0]); res.json({ token, user: { id: rows[0].id, name: rows[0].name, role: rows[0].role } }); });
app.get('/api/me', auth(), (req, res) => res.json({ user: req.user }));

app.get('/api/stores', auth(['ops', 'admin']), async (_req, res) => res.json(await q('SELECT id,name,address,manager_name,status,created_at FROM stores ORDER BY id')));
app.post('/api/stores', auth(['admin']), async (req, res) => { const { name, address = '', managerName = '', code } = req.body; if (!name || !code) return res.status(400).json({ error: '门店名称和口令必填' }); const r = await execSql('INSERT INTO stores(name,address,manager_name,login_code) VALUES(?,?,?,?)', [name, address, managerName, code]); if (managerName) await execSql("INSERT INTO users(name,store_id,role) VALUES(?,?, 'store')", [managerName, r.insertId]); await log(req, 'create', 'stores', r.insertId, { name }); changed(); res.json({ id: r.insertId, name, address, manager_name: managerName, status: 'active' }); });
app.patch('/api/stores/:id', auth(['admin']), async (req, res) => { const { name = null, address = null, managerName = null, code = null, status = null } = req.body; await execSql('UPDATE stores SET name=COALESCE(?,name),address=COALESCE(?,address),manager_name=COALESCE(?,manager_name),login_code=COALESCE(?,login_code),status=COALESCE(?,status) WHERE id=?', [name, address, managerName, code, status, req.params.id]); if (managerName) await execSql("UPDATE users SET name=? WHERE store_id=? AND role='store'", [managerName, req.params.id]); await log(req, 'update', 'stores', req.params.id, { changed: req.body }); changed(); res.json((await q('SELECT * FROM stores WHERE id=?', [req.params.id]))[0]); });
app.delete('/api/stores/:id', auth(['admin']), async (req, res) => { if (req.body.confirm !== 'DELETE') return res.status(400).json({ error: '需要二次确认' }); await execSql("UPDATE stores SET status='archived' WHERE id=?", [req.params.id]); await log(req, 'archive', 'stores', req.params.id); changed(); res.json({ ok: true }); });
app.get('/api/users', auth(['admin']), async (_req, res) => res.json(await q("SELECT u.id,u.name,u.store_id,u.role,s.name AS store_name,u.created_at FROM users u LEFT JOIN stores s ON s.id=u.store_id WHERE u.role='store' ORDER BY s.id,u.id")));
app.get('/api/admin/accounts', auth(['admin']), async (_req,res) => res.json(await q("SELECT id,name,role,created_at FROM users WHERE role IN ('ops','admin') ORDER BY role,id")));
app.patch('/api/admin/accounts/:id', auth(['admin']), async (req,res) => { const rows=await q("SELECT id,name,role FROM users WHERE id=? AND role IN ('ops','admin')",[req.params.id]); if(!rows.length)return res.status(404).json({error:'账号不存在'}); const {name,password}=req.body; if(!String(name||'').trim())return res.status(400).json({error:'账号名称不能为空'}); if(password!==undefined && String(password).length<6)return res.status(400).json({error:'口令至少需要6位'}); const hash=password!==undefined?await bcrypt.hash(String(password),10):null; await execSql('UPDATE users SET name=?,password_hash=COALESCE(?,password_hash) WHERE id=?',[String(name).trim(),hash,req.params.id]); await log(req,'update','users',req.params.id,{name, passwordChanged: password!==undefined}); changed(); res.json((await q('SELECT id,name,role,created_at FROM users WHERE id=?',[req.params.id]))[0]); });
app.post('/api/users', auth(['admin']), async (req, res) => { const { name, storeId } = req.body; if (!name || !storeId) return res.status(400).json({ error: '姓名和门店必填' }); const r = await execSql("INSERT INTO users(name,store_id,role) VALUES(?,?, 'store')", [name, storeId]); await log(req, 'create', 'users', r.insertId, { name, storeId }); changed(); res.json({ id: r.insertId, name, store_id: storeId, role: 'store' }); });
app.delete('/api/users/:id', auth(['admin']), async (req, res) => { if (req.body.confirm !== 'DELETE') return res.status(400).json({ error: '需要二次确认' }); await execSql("DELETE FROM users WHERE id=? AND role='store'", [req.params.id]); await log(req, 'delete', 'users', req.params.id); changed(); res.json({ ok: true }); });
app.get('/api/report-fields', auth(), async (_req, res) => res.json(await q('SELECT * FROM report_fields WHERE enabled=1 ORDER BY sort_order,id')));
app.put('/api/report-fields', auth(['admin']), async (req, res) => { const fields = req.body.fields || []; const keys = new Set(); for (const f of fields) { if (!f.label || !f.key || keys.has(f.key)) return res.status(400).json({ error: '日报字段名称或唯一键重复' }); keys.add(f.key); } await execSql('UPDATE report_fields SET enabled=0'); for (let i = 0; i < fields.length; i++) { const f = fields[i]; await execSql('INSERT INTO report_fields(label,`key`,field_type,unit,required,sort_order,enabled) VALUES(?,?,?,?,?,?,1) ON DUPLICATE KEY UPDATE label=VALUES(label),field_type=VALUES(field_type),unit=VALUES(unit),required=VALUES(required),sort_order=VALUES(sort_order),enabled=1', [f.label, f.key, f.field_type || 'number', f.unit || '', !!f.required, i + 1]); } await log(req, 'update', 'report_fields', 'all', { count: fields.length }); changed(); res.json({ ok: true }); });

app.get('/api/reports', auth(), async (req, res) => { const conditions = []; const params = []; if (req.user.role === 'store') { conditions.push('r.store_id=?'); params.push(req.user.storeId); } else if (req.query.storeId) { conditions.push('r.store_id=?'); params.push(req.query.storeId); } if (req.query.month) { conditions.push("DATE_FORMAT(r.report_date,'%Y-%m')=?"); params.push(req.query.month); } const rows = await q(`SELECT r.*,s.name AS store_name,COALESCE(r.submitted_by_name,u.name) AS submitter_name FROM daily_reports r JOIN stores s ON s.id=r.store_id LEFT JOIN users u ON u.id=r.submitted_by ${conditions.length ? 'WHERE ' + conditions.join(' AND ') : ''} ORDER BY r.report_date DESC,r.id DESC${req.user.role==='admin'&&!req.query.month?'':' LIMIT 500'}`, params); res.json(rows.map(r => ({ ...r, payload: json(r.payload) }))); });
app.delete('/api/reports/:id', auth(['admin']), async (req, res) => { const rows = await q('SELECT id,store_id,report_date FROM daily_reports WHERE id=?', [req.params.id]); if (!rows.length) return res.status(404).json({ error: '日报不存在' }); const r = rows[0]; await execSql('DELETE FROM daily_reports WHERE id=?', [r.id]); await execSql("UPDATE tasks SET actual_value=0,status='pending' WHERE store_id=? AND task_date=?", [r.store_id, r.report_date]); await log(req, 'delete', 'daily_reports', r.id, { storeId: r.store_id, date: r.report_date }); changed(); res.json({ ok: true }); });
app.post('/api/reports', auth(['store', 'admin']), async (req, res) => { const storeId = req.user.role === 'store' ? req.user.storeId : Number(req.body.storeId); const { date, payload = {} } = req.body; if (!storeId || !date) return res.status(400).json({ error: '缺少门店或日期' }); const requiredFields = await q('SELECT `key`,label,field_type FROM report_fields WHERE enabled=1 AND required=1'); const missing = requiredFields.filter(f => payload[f.key] === undefined || payload[f.key] === null || String(payload[f.key]).trim() === ''); if (missing.length) return res.status(400).json({ error: '请填写必填项：' + missing.map(f=>f.label).join('、'), missing: missing.map(f=>f.key) }); const old = await q('SELECT id,version FROM daily_reports WHERE store_id=? AND report_date=?', [storeId, date]); let reportId; if (old.length) { reportId = old[0].id; await execSql('UPDATE daily_reports SET payload=?,submitted_by=?,submitted_by_name=?,version=version+1 WHERE id=?', [JSON.stringify(payload), req.user.id || null, req.user.name, reportId]); } else { reportId = (await execSql('INSERT INTO daily_reports(store_id,report_date,submitted_by,submitted_by_name,payload,version) VALUES(?,?,?,?,?,1)', [storeId, date, req.user.id || null, req.user.name, JSON.stringify(payload)])).insertId; } const revenue = reportRevenue(payload); await execSql("UPDATE tasks SET actual_value=?,status=IF(? >= target_value,'done','pending') WHERE store_id=? AND task_date=?", [revenue, revenue, storeId, date]); await log(req, old.length ? 'update' : 'create', 'daily_reports', reportId, { date }); changed(); res.json((await q('SELECT * FROM daily_reports WHERE id=?', [reportId]))[0]); });

app.get('/api/goals', auth(), async (req, res) => { const store = req.user.role === 'store' ? req.user.storeId : req.query.storeId; const month = req.query.month || new Date().toISOString().slice(0, 7); const params = [month]; let where = 'g.month=?'; if (store) { where += ' AND g.store_id=?'; params.push(store); } res.json(await q(`SELECT g.*,s.name AS store_name FROM monthly_goals g JOIN stores s ON s.id=g.store_id WHERE ${where} ORDER BY g.id`, params)); });
app.post('/api/goals', auth(['ops', 'admin']), async (req, res) => { const { storeId, month, goalValue, rule = 'average', title = '营业额目标', customTargets } = req.body; if (!storeId || !month || Number(goalValue) <= 0) return res.status(400).json({ error: '门店、月份、目标值必填' }); const [y, m] = month.split('-').map(Number); const days = new Date(y, m, 0).getDate(); let targets; if (rule === 'custom') { if (!Array.isArray(customTargets) || customTargets.length !== days) return res.status(400).json({ error: `自定义目标必须提供${days}天数据` }); targets = customTargets.map(Number); if (targets.some(x => !Number.isFinite(x) || x < 0) || Math.abs(targets.reduce((a, b) => a + b, 0) - Number(goalValue)) > 0.01) return res.status(400).json({ error: '每日目标之和必须等于月目标' }); } else { const weights = Array.from({ length: days }, (_, i) => rule === 'weekendWeight' && [0, 6].includes(new Date(y, m - 1, i + 1).getDay()) ? 1.5 : 1); const sum = weights.reduce((a, b) => a + b, 0); targets = weights.map(w => Number(goalValue) * w / sum); } await execSql('INSERT INTO monthly_goals(store_id,`month`,goal_type,goal_value,rule,created_by) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE goal_value=VALUES(goal_value),rule=VALUES(rule),created_by=VALUES(created_by)', [storeId, month, 'revenue', goalValue, rule, req.user.id]); const goal = (await q('SELECT * FROM monthly_goals WHERE store_id=? AND `month`=? AND goal_type=?', [storeId, month, 'revenue']))[0]; for (let d = 1; d <= days; d++) { const dt = `${month}-${String(d).padStart(2, '0')}`; await execSql('INSERT INTO tasks(store_id,goal_id,title,target_value,unit,task_date) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE target_value=VALUES(target_value),title=VALUES(title)', [storeId, goal.id, title, targets[d - 1], '元', dt]); } await execSql("UPDATE tasks t JOIN daily_reports r ON r.store_id=t.store_id AND r.report_date=t.task_date SET t.actual_value=COALESCE(CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.revenue')) AS DECIMAL(14,2)),0), t.status=IF(COALESCE(CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.revenue')) AS DECIMAL(14,2)),0) >= t.target_value,'done','pending') WHERE t.store_id=? AND t.task_date BETWEEN ? AND ?", [storeId, `${month}-01`, `${month}-${String(days).padStart(2, '0')}`]); await log(req, 'upsert', 'monthly_goals', goal.id, { month, goalValue, rule }); changed(); res.json(goal); });
app.get('/api/tasks', auth(), async (req, res) => { const store = req.user.role === 'store' ? req.user.storeId : req.query.storeId; const month = req.query.month || new Date().toISOString().slice(0, 7); const params = [month]; let where = "DATE_FORMAT(t.task_date,'%Y-%m')=?"; if (store) { where += ' AND t.store_id=?'; params.push(store); } res.json(await q(`SELECT t.*,s.name AS store_name FROM tasks t JOIN stores s ON s.id=t.store_id WHERE ${where} ORDER BY t.task_date`, params)); });
app.patch('/api/tasks/:id', auth(['ops', 'admin']), async (req, res) => { const { targetValue, title } = req.body; if (targetValue !== undefined && Number(targetValue) < 0) return res.status(400).json({ error: '目标不能为负数' }); await execSql('UPDATE tasks SET target_value=COALESCE(?,target_value),title=COALESCE(?,title) WHERE id=?', [targetValue === undefined ? null : Number(targetValue), title || null, req.params.id]); await log(req, 'update', 'tasks', req.params.id, req.body); changed(); res.json((await q('SELECT * FROM tasks WHERE id=?', [req.params.id]))[0]); });

app.get('/api/ranking-metrics', auth(), async (_req,res)=>res.json(await q('SELECT * FROM ranking_metrics WHERE enabled=1 ORDER BY sort_order,id')));
app.put('/api/ranking-metrics', auth(['admin']), async (req,res)=>{const metrics=Array.isArray(req.body.metrics)?req.body.metrics:[];for(let i=0;i<metrics.length;i++){const m=metrics[i];if(!m.metric_key||!m.label||!m.source_key)return res.status(400).json({error:'排行名称和数据字段不能为空'});await execSql('INSERT INTO ranking_metrics(metric_key,label,unit,source_key,aggregation,enabled,sort_order) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),unit=VALUES(unit),source_key=VALUES(source_key),aggregation=VALUES(aggregation),enabled=VALUES(enabled),sort_order=VALUES(sort_order)',[m.metric_key,m.label,m.unit||'',m.source_key,m.aggregation||'sum',m.enabled!==false,i+1]);}await execSql('UPDATE ranking_metrics SET enabled=0 WHERE metric_key NOT IN ('+metrics.map(()=>'?').join(',')+')',metrics.map(m=>m.metric_key));await log(req,'update','ranking_metrics','all',{count:metrics.length});changed();res.json(await q('SELECT * FROM ranking_metrics WHERE enabled=1 ORDER BY sort_order,id'));});
app.get('/api/ai/settings', auth(['admin']), async (_req,res)=>{const r=(await q('SELECT id,endpoint,model,enabled,updated_at,IF(api_key IS NULL OR api_key="",0,1) AS has_key FROM ai_settings WHERE id=1'))[0];res.json(r||{id:1,endpoint:'',model:'',enabled:false,has_key:0});});
app.put('/api/ai/settings', auth(['admin']), async (req,res)=>{const {endpoint='',model='',apiKey,enabled=false}=req.body;if(endpoint&&!/^https?:\/\//i.test(endpoint))return res.status(400).json({error:'AI 接口必须是 http 或 https 地址'});const key=apiKey===undefined?null:String(apiKey||'');await execSql('INSERT INTO ai_settings(id,endpoint,model,api_key,enabled,updated_by) VALUES(1,?,?,?,?,?) ON DUPLICATE KEY UPDATE endpoint=VALUES(endpoint),model=VALUES(model),api_key=CASE WHEN ? IS NULL THEN api_key WHEN ?="" THEN NULL ELSE ? END,enabled=VALUES(enabled),updated_by=VALUES(updated_by)',[endpoint,model,key,!!enabled,req.user.id,apiKey===undefined?null:key,key,key,]);await log(req,'update','ai_settings','1',{endpoint,model,enabled,apiKeyChanged:apiKey!==undefined});changed();res.json({ok:true});});
app.post('/api/ai/analyze', auth(), async (req,res)=>{const cfg=(await q('SELECT * FROM ai_settings WHERE id=1'))[0]||{};const endpoint=cfg.endpoint||process.env.OPENAI_API_BASE||'';const key=cfg.api_key||process.env.OPENAI_API_KEY||'';const model=cfg.model||'gpt-4o-mini';if(!endpoint||!key||!cfg.enabled&&!(process.env.OPENAI_API_KEY&&process.env.OPENAI_API_BASE))return res.status(400).json({error:'AI 尚未配置或未启用'});const from=req.body.from||new Date().toISOString().slice(0,7)+'-01',to=req.body.to||new Date().toISOString().slice(0,10);const sid=req.user.role==='store'?req.user.storeId:(req.body.storeId||'all');const rows=await q(`SELECT r.report_date,s.name AS store_name,r.submitted_by_name,r.payload FROM daily_reports r JOIN stores s ON s.id=r.store_id WHERE r.report_date BETWEEN ? AND ? ${sid!=='all'?'AND r.store_id=?':''} ORDER BY r.report_date`,sid==='all'?[from,to]:[from,to,Number(sid)]);const prompt=String(req.body.prompt||'请分析经营趋势、异常指标、门店差异和下一步行动建议。');const data=rows.map(r=>({date:r.report_date,store:r.store_name,submitter:r.submitted_by_name,payload:json(r.payload)}));try{const rr=await fetch(endpoint.replace(/\/$/, '')+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+key},body:JSON.stringify({model,temperature:0.2,messages:[{role:'system',content:'你是ONEIRA烘焙连锁运营分析助手。只基于提供的数据，使用简体中文，输出结论、异常、建议，避免编造。'},{role:'user',content:prompt+'\n数据：'+JSON.stringify(data)}]})});const out=await rr.json();if(!rr.ok)throw new Error(out.error?.message||'AI接口请求失败');res.json({content:out.choices?.[0]?.message?.content||'AI未返回分析结果',from,to,rows:data.length});}catch(e){res.status(502).json({error:'AI分析失败：'+e.message})}});
app.get('/api/analytics', auth(['store','ops', 'admin']), async (req, res) => {
  const rankingConfigs = await q('SELECT metric_key,source_key,aggregation FROM ranking_metrics WHERE enabled=1 ORDER BY sort_order,id');
  const requestedStore = req.user.role==='store' ? String(req.user.storeId) : (req.query.storeId || 'all');
  const now = new Date();
  const validDate = value => /^\d{4}-\d{2}-\d{2}$/.test(value || '');
  const to = validDate(req.query.to) ? req.query.to : now.toISOString().slice(0, 10);
  const from = validDate(req.query.from) ? req.query.from : `${to.slice(0, 7)}-01`;
  if (from > to) return res.status(400).json({ error: '开始日期不能晚于结束日期' });
  const params = [from, to];
  let filter = 'WHERE r.report_date BETWEEN ? AND ?';
  if (requestedStore && requestedStore !== 'all') { filter += ' AND r.store_id=?'; params.push(Number(requestedStore)); }
  const metric = req.query.metric || 'revenue';
  const byStore = await q(`SELECT r.store_id,s.name AS store_name,
    COUNT(*) AS report_days,
    COALESCE(SUM(COALESCE(CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.totalRevenue')) AS DECIMAL(14,2)),CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.revenue')) AS DECIMAL(14,2)))),0) AS revenue,
    COALESCE(SUM(CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.orders')) AS DECIMAL(14,2))),0) AS orders,
    COALESCE(AVG(CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.wasteRate')) AS DECIMAL(14,2))),0) AS waste_rate,
    COALESCE(SUM(CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.members')) AS DECIMAL(14,2))),0) AS members
    FROM daily_reports r JOIN stores s ON s.id=r.store_id ${filter}
    GROUP BY r.store_id,s.name ORDER BY ${metric === 'orders' ? 'orders' : metric === 'wasteRate' ? 'waste_rate' : metric === 'members' ? 'members' : 'revenue'} DESC`, params);
  const byDay = await q(`SELECT DATE_FORMAT(r.report_date,'%Y-%m-%d') AS day,
    COALESCE(SUM(COALESCE(CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.totalRevenue')) AS DECIMAL(14,2)),CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.revenue')) AS DECIMAL(14,2)))),0) AS revenue,
    COALESCE(SUM(CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.orders')) AS DECIMAL(14,2))),0) AS orders,
    COALESCE(AVG(CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.wasteRate')) AS DECIMAL(14,2))),0) AS waste_rate,
    COALESCE(SUM(CAST(JSON_UNQUOTE(JSON_EXTRACT(r.payload,'$.members')) AS DECIMAL(14,2))),0) AS members
    FROM daily_reports r ${filter} GROUP BY r.report_date ORDER BY r.report_date`, params);
  const totals = byStore.reduce((acc, row) => ({
    revenue: acc.revenue + Number(row.revenue || 0), orders: acc.orders + Number(row.orders || 0),
    members: acc.members + Number(row.members || 0), reportDays: acc.reportDays + Number(row.report_days || 0),
    wasteRateSum: acc.wasteRateSum + Number(row.waste_rate || 0)
  }), { revenue: 0, orders: 0, members: 0, reportDays: 0, wasteRateSum: 0 });
  const result = {
    from, to, metric,
    totals: { revenue: totals.revenue, orders: totals.orders, members: totals.members, reportDays: totals.reportDays, wasteRate: byStore.length ? totals.wasteRateSum / byStore.length : 0, avgOrderValue: totals.orders ? totals.revenue / totals.orders : 0 },
    byStore: byStore.map(row => ({ storeId: row.store_id, storeName: row.store_name, reportDays: Number(row.report_days || 0), revenue: Number(row.revenue || 0), orders: Number(row.orders || 0), wasteRate: Number(row.waste_rate || 0), members: Number(row.members || 0), avgOrderValue: Number(row.orders || 0) ? Number(row.revenue || 0) / Number(row.orders || 0) : 0, metricValues: {} })),
    byDay: byDay.map(row => ({ day: row.day, revenue: Number(row.revenue || 0), orders: Number(row.orders || 0), wasteRate: Number(row.waste_rate || 0), members: Number(row.members || 0), avgOrderValue: Number(row.orders || 0) ? Number(row.revenue || 0) / Number(row.orders || 0) : 0 })), details: (await q(`SELECT r.id,r.report_date,r.created_at,r.updated_at,r.submitted_by_name,s.name AS store_name,r.payload FROM daily_reports r JOIN stores s ON s.id=r.store_id WHERE r.report_date BETWEEN ? AND ? ${requestedStore&&requestedStore!=='all'?'AND r.store_id=?':''} ORDER BY r.report_date DESC,r.id DESC`, requestedStore&&requestedStore!=='all'?[from,to,Number(requestedStore)]:[from,to])).map(r=>({...r,payload:json(r.payload)}))
  };
  const detailRows = result.details || [];
  for (const row of result.byStore) { const items=detailRows.filter(d=>Number(d.store_id||0)===Number(row.storeId)||d.store_name===row.storeName); for (const cfg of rankingConfigs) { const vals=items.map(d=>Number((d.payload||{})[cfg.source_key])).filter(Number.isFinite); row.metricValues[cfg.metric_key]=cfg.aggregation==='avg'?(vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0):vals.reduce((a,b)=>a+b,0); } }
  result.byStore.sort((a,b)=>Number(b.metricValues[metric]??metricValueForLegacy(b,metric))-Number(a.metricValues[metric]??metricValueForLegacy(a,metric)));
  res.json(result);
});
function metricValueForLegacy(row,metric){return metric==='orders'?Number(row.orders||0):metric==='wasteRate'?Number(row.wasteRate||0):metric==='members'?Number(row.members||0):Number(row.revenue||0)}

app.get('/api/reviews', auth(), async (req, res) => {
  const params = []; let where = '1=1';
  if (req.user.role === 'store') { where += ' AND r.store_id=?'; params.push(req.user.storeId); }
  else if (req.query.storeId && req.query.storeId !== 'all') { where += ' AND r.store_id=?'; params.push(Number(req.query.storeId)); }
  if (req.query.periodType) { where += ' AND r.period_type=?'; params.push(req.query.periodType); }
  if (req.query.periodKey) { where += ' AND r.period_key=?'; params.push(req.query.periodKey); }
  res.json(await q(`SELECT r.*,s.name AS store_name,u.name AS author_user_name FROM period_reviews r JOIN stores s ON s.id=r.store_id LEFT JOIN users u ON u.id=r.author_id WHERE ${where} ORDER BY r.period_key DESC,r.updated_at DESC LIMIT 300`, params));
});
app.post('/api/reviews', auth(['store','ops','admin']), async (req, res) => {
  const storeId = req.user.role === 'store' ? req.user.storeId : Number(req.body.storeId);
  const { periodType, periodKey, title='', content='', highlights='', blockers='', nextActions='' } = req.body;
  if (!storeId || !['week','month'].includes(periodType) || !periodKey || !String(content).trim()) return res.status(400).json({ error: '门店、周期和复盘内容必填' });
  const existing = await q('SELECT id FROM period_reviews WHERE store_id=? AND period_type=? AND period_key=? AND author_id=? LIMIT 1', [storeId, periodType, periodKey, req.user.id || null]);
  let id;
  if (existing.length) { id=existing[0].id; await execSql('UPDATE period_reviews SET title=?,content=?,highlights=?,blockers=?,next_actions=?,author_role=? WHERE id=?', [title,content,highlights,blockers,nextActions,req.user.role,id]); }
  else { id=(await execSql('INSERT INTO period_reviews(store_id,author_id,author_role,period_type,period_key,title,content,highlights,blockers,next_actions) VALUES(?,?,?,?,?,?,?,?,?,?)', [storeId,req.user.id||null,req.user.role,periodType,periodKey,title,content,highlights,blockers,nextActions])).insertId; }
  await log(req, existing.length ? 'update' : 'create', 'period_reviews', id, { storeId, periodType, periodKey }); changed(); res.json((await q('SELECT r.*,s.name AS store_name FROM period_reviews r JOIN stores s ON s.id=r.store_id WHERE r.id=?',[id]))[0]);
});
app.delete('/api/reviews/:id', auth(['ops','admin','store']), async (req,res) => { const rows=await q('SELECT * FROM period_reviews WHERE id=?',[req.params.id]); if(!rows.length)return res.status(404).json({error:'复盘不存在'}); if(req.user.role==='store'&&(rows[0].store_id!==req.user.storeId||rows[0].author_id!==req.user.id))return res.status(403).json({error:'无权限'}); await execSql('DELETE FROM period_reviews WHERE id=?',[req.params.id]); await log(req,'delete','period_reviews',req.params.id); changed(); res.json({ok:true}); });
app.get('/api/annotations', auth(), async (req,res) => {
  const params=[]; let where='1=1';
  if(req.user.role==='store'){where+=' AND a.store_id=?';params.push(req.user.storeId)} else if(req.query.storeId&&req.query.storeId!=='all'){where+=' AND a.store_id=?';params.push(Number(req.query.storeId))}
  if(req.query.month){where+=" AND DATE_FORMAT(a.annotation_date,'%Y-%m')=?";params.push(req.query.month)}
  res.json(await q(`SELECT a.*,s.name AS store_name FROM calendar_annotations a JOIN stores s ON s.id=a.store_id WHERE ${where} ORDER BY a.annotation_date DESC,a.created_at DESC LIMIT 500`,params));
});
app.post('/api/annotations', auth(['store','ops','admin']), async (req,res)=>{ const storeId=req.user.role==='store'?req.user.storeId:Number(req.body.storeId); const {date,type='note',title='',content='',reminderAt=null}=req.body; if(!storeId||!date||!String(content).trim())return res.status(400).json({error:'日期和标注内容必填'}); const r=await execSql('INSERT INTO calendar_annotations(store_id,annotation_date,author_id,author_name,annotation_type,title,content,reminder_at) VALUES(?,?,?,?,?,?,?,?)',[storeId,date,req.user.id||null,req.user.name,type,title,content,reminderAt||null]); await log(req,'create','calendar_annotations',r.insertId,{storeId,date,type});changed();res.json((await q('SELECT a.*,s.name AS store_name FROM calendar_annotations a JOIN stores s ON s.id=a.store_id WHERE a.id=?',[r.insertId]))[0]); });
app.patch('/api/annotations/:id', auth(['store','ops','admin']), async(req,res)=>{const rows=await q('SELECT * FROM calendar_annotations WHERE id=?',[req.params.id]);if(!rows.length)return res.status(404).json({error:'标注不存在'});if(req.user.role==='store'&&(rows[0].store_id!==req.user.storeId||rows[0].author_id!==req.user.id))return res.status(403).json({error:'无权限'});const {type,title='',content,reminderAt=null,status}=req.body;await execSql('UPDATE calendar_annotations SET annotation_type=COALESCE(?,annotation_type),title=COALESCE(?,title),content=COALESCE(?,content),reminder_at=?,status=COALESCE(?,status) WHERE id=?',[type||null,title,content||null,reminderAt||null,status||null,req.params.id]);await log(req,'update','calendar_annotations',req.params.id,req.body);changed();res.json({ok:true});});
app.delete('/api/annotations/:id', auth(['store','ops','admin']), async(req,res)=>{const rows=await q('SELECT * FROM calendar_annotations WHERE id=?',[req.params.id]);if(!rows.length)return res.status(404).json({error:'标注不存在'});if(req.user.role==='store'&&(rows[0].store_id!==req.user.storeId||rows[0].author_id!==req.user.id))return res.status(403).json({error:'无权限'});await execSql('DELETE FROM calendar_annotations WHERE id=?',[req.params.id]);await log(req,'delete','calendar_annotations',req.params.id);changed();res.json({ok:true});});
app.get('/api/issues', auth(), async (req, res) => { const params = []; let where = ''; if (req.user.role === 'store') { where = 'WHERE i.store_id=?'; params.push(req.user.storeId); } res.json(await q(`SELECT i.*,s.name AS store_name FROM issues i LEFT JOIN stores s ON s.id=i.store_id ${where} ORDER BY i.created_at DESC LIMIT 300`, params)); });
app.post('/api/issues', auth(['store','ops','admin']), async (req, res) => { const storeId=req.user.role==='store'?req.user.storeId:Number(req.body.storeId); const { type = '问题', content = '' } = req.body; if (!storeId || !String(content).trim()) return res.status(400).json({ error: '门店和反馈内容必填' }); const r = await execSql('INSERT INTO issues(store_id,submitter_name,type,content) VALUES(?,?,?,?)', [storeId, req.user.name, type, content]); await log(req, 'create', 'issues', r.insertId); changed(); res.json((await q('SELECT * FROM issues WHERE id=?', [r.insertId]))[0]); });
app.patch('/api/issues/:id', auth(['store','ops','admin']), async (req, res) => { const rows=await q('SELECT * FROM issues WHERE id=?',[req.params.id]); if(!rows.length)return res.status(404).json({error:'反馈不存在'}); if(req.user.role==='store'&&rows[0].store_id!==req.user.storeId)return res.status(403).json({error:'无权限'}); const {type,content,status,note}=req.body; await execSql("UPDATE issues SET type=COALESCE(?,type),content=COALESCE(?,content),status=COALESCE(?,status),handler_id=CASE WHEN ? IS NOT NULL THEN ? ELSE handler_id END,handled_at=CASE WHEN ? IN ('resolved','closed') THEN NOW() ELSE handled_at END,handling_note=COALESCE(?,handling_note) WHERE id=?", [type||null,content||null,status||null,req.user.role==='store'?null:req.user.id,req.user.role==='store'?null:req.user.id,status||null,note||null,req.params.id]); await log(req, 'update', 'issues', req.params.id, { type,content,status,note }); changed(); res.json((await q('SELECT * FROM issues WHERE id=?',[req.params.id]))[0]); });
app.delete('/api/issues/:id', auth(['store','ops','admin']), async (req,res)=>{const rows=await q('SELECT * FROM issues WHERE id=?',[req.params.id]);if(!rows.length)return res.status(404).json({error:'反馈不存在'});if(req.user.role==='store'&&rows[0].store_id!==req.user.storeId)return res.status(403).json({error:'无权限'});await execSql('DELETE FROM issues WHERE id=?',[req.params.id]);await log(req,'delete','issues',req.params.id);changed();res.json({ok:true});});
app.get('/api/audit', auth(['admin']), async (_req, res) => res.json(await q('SELECT a.*,u.name AS user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 300')));
app.get('/api/export/reports.csv', async (req, res) => { try { const u = jwt.verify(req.query.token || '', secret()); if (!['store','ops', 'admin'].includes(u.role)) throw new Error('forbidden'); } catch { return res.status(401).json({ error: '登录已失效' }); } const month = req.query.month || new Date().toISOString().slice(0, 7); const storeClause=u.role==='store'?' AND r.store_id=?':''; const rows = await q("SELECT r.report_date,s.name AS store_name,r.payload,COALESCE(r.submitted_by_name,u.name) AS submitter_name FROM daily_reports r JOIN stores s ON s.id=r.store_id LEFT JOIN users u ON u.id=r.submitted_by WHERE DATE_FORMAT(r.report_date,'%Y-%m')=?"+storeClause+" ORDER BY r.report_date,s.id", u.role==='store'?[month,u.storeId]:[month]); const lines = ['日期,门店,总营业额,优惠折扣,实收金额,平台收入,会员卡消费,会员卡充值,现金,到店微信支付宝云闪付,试吃数量,报损数量,试吃金额,试吃占比,报损金额,报损占比,会员实体卡余量,提交人']; for (const r of rows) { const p = json(r.payload); lines.push([r.report_date, r.store_name, p.totalRevenue ?? p.revenue ?? '', p.discounts ?? '', p.received ?? '', p.platformTotal ?? '', p.memberCardConsumption ?? '', p.memberCardRecharge ?? '', p.cash ?? '', p.onsiteDigital ?? '', p.trialCount ?? '', p.wasteCount ?? '', p.trialAmount ?? '', p.trialRatio ?? '', p.wasteAmount ?? '', p.wasteRatio ?? '', p.physicalCardBalance ?? '', r.submitter_name || ''].map(x => '"' + String(x).replaceAll('"', '""') + '"').join(',')); } res.setHeader('Content-Type', 'text/csv; charset=utf-8'); res.setHeader('Content-Disposition', `attachment; filename="oneira-reports-${month}.csv"`); res.send('\ufeff' + lines.join('\n')); });

io.on('connection', socket => socket.emit('ready', { ok: true }));
app.use((req, res, next) => { if (req.method !== 'GET' || req.path.startsWith('/api/')) return next(); res.sendFile(path.join(__dirname, 'public', 'index.html')); });
async function boot() { await migrateAndSeed(); server.listen(PORT, '0.0.0.0', () => console.log(`ONEIRA Manus Space running on ${PORT}`)); }
boot().catch(error => { console.error(error); process.exit(1); });
